name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install yarn
        run: |
          npm install -g yarn

      # Cypress action caches dependencies too.
      - name: install, build and E2E tests
        uses: cypress-io/github-action@v1
        with:
          build: yarn build
          start: yarn serve
          wait-on: "http://localhost:4000"

      - name: lint and unit test
        run: |
          yarn lint
          yarn test
        env:
          CI: true
