name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: install and cache dependencies
        uses: cypress-io/github-action@v5
        with:
          runTests: false

      - name: lint and unit test
        run: |
          yarn lint
          yarn test
        env:
          CI: true

      - name: run E2E tests
        uses: cypress-io/github-action@v5
        with:
          install: false
          build: yarn build
          start: yarn serve
          wait-on: "http://localhost:8080"

      - name: deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: public
          clean: true
