name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.8.1-chrome80-ff72

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: install and cache dependencies
        uses: cypress-io/github-action@v1
        with:
          runTests: false

      - name: lint and unit test
        run: |
          yarn lint
          yarn test
        env:
          CI: true

      - name: build
        run: |
          yarn build

      - name: run E2E tests on Chrome
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          install: false
          start: yarn serve
          wait-on: "http://localhost:4000"

      - name: run E2E tests on Firefox
        uses: cypress-io/github-action@v1
        with:
          browser: firefox
          install: false
          start: yarn serve
          wait-on: "http://localhost:4000"

      - name: deploy
        if: github.ref == 'refs/heads/source'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: public
          CLEAN: true
